"""Generate a self-contained Google Colab fine-tuning notebook.

Colab has no official API for submitting jobs, so instead of driving it
remotely we emit a ready-to-run ``.ipynb``. The notebook mounts Google Drive
(dataset in / trained model out), installs ``bosesph`` from GitHub, and calls
the existing :func:`bosesph.finetune.finetune_model` on Colab's GPU.

This module is intentionally dependency-free: an ``.ipynb`` is just JSON, so it
is built with the stdlib ``json`` module and needs none of the heavy ``[train]``
extras (torch/transformers). Generating a notebook works on a base install.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

from pydantic import BaseModel

NBFORMAT = 4
NBFORMAT_MINOR = 5

# Editable Drive base used to derive per-dataset paths in the CLI.
DEFAULT_DRIVE_BASE = "/content/drive/MyDrive/bosesph"
DEFAULT_REPO_URL = "https://github.com/klydddd/asteria-classmates.git"
DEFAULT_REPO_REF = "main"


class ColabExportConfig(BaseModel):
    """Everything needed to render a Colab fine-tuning notebook.

    Mirrors the training parameters of
    :func:`bosesph.finetune.finetune_model` plus Colab-specific fields for the
    GitHub install source and the Google Drive dataset/output locations.
    """

    # Training parameters (mirrors finetune_model).
    base_model: str
    language: str
    epochs: int
    max_steps: int | None
    batch_size: int
    learning_rate: float
    train_split: str
    eval_split: str
    gradient_checkpointing: bool
    optim: str
    use_lora: bool
    lora_r: int
    lora_alpha: int
    lora_dropout: float

    # Colab-specific.
    repo_url: str = DEFAULT_REPO_URL
    repo_ref: str = DEFAULT_REPO_REF
    drive_dataset_path: str
    drive_output_path: str
    fp16: bool = True


# ---------------------------------------------------------------------------
# Cell helpers
# ---------------------------------------------------------------------------


def _markdown_cell(source: str) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source,
    }


def _code_cell(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


# ---------------------------------------------------------------------------
# Notebook assembly
# ---------------------------------------------------------------------------


def _pip_install_spec(config: ColabExportConfig) -> str:
    return f"git+{config.repo_url}@{config.repo_ref}#egg=bosesph-toolkit[train]"


def _config_block(config: ColabExportConfig) -> str:
    """Render the editable Python config cell (params baked from CLI args)."""
    return textwrap.dedent(
        f"""\
        # === Edit these if your Drive layout differs ===
        dataset_dir = {config.drive_dataset_path!r}
        output_dir = {config.drive_output_path!r}

        # === Training hyperparameters ===
        base_model = {config.base_model!r}
        language = {config.language!r}
        epochs = {config.epochs!r}
        max_steps = {config.max_steps!r}
        batch_size = {config.batch_size!r}
        learning_rate = {config.learning_rate!r}
        train_split = {config.train_split!r}
        eval_split = {config.eval_split!r}
        gradient_checkpointing = {config.gradient_checkpointing!r}
        optim = {config.optim!r}
        use_lora = {config.use_lora!r}
        lora_r = {config.lora_r!r}
        lora_alpha = {config.lora_alpha!r}
        lora_dropout = {config.lora_dropout!r}
        fp16 = {config.fp16!r}
        """
    )


def build_notebook(config: ColabExportConfig) -> dict[str, Any]:
    """Build the Colab notebook as an nbformat-v4 dict."""
    cells: list[dict[str, Any]] = [
        _markdown_cell(
            textwrap.dedent(
                f"""\
                # BosesPH Fine-Tuning on Google Colab

                This notebook fine-tunes a Whisper model on a BosesPH dataset
                using Colab's GPU. Generated by `bosesph export-colab`.

                **Before you run:**
                1. Upload your built dataset folder to Google Drive at:
                   `{config.drive_dataset_path}`
                   (it should contain `{config.train_split}.csv`,
                   `{config.eval_split}.csv`, and the audio files).
                2. Set the runtime to GPU: **Runtime → Change runtime type → GPU**.
                3. Run all cells (**Runtime → Run all**).

                The trained model is written back to Drive at:
                `{config.drive_output_path}`

                > If the repo `{config.repo_url}` is private, change the install
                > cell to include a GitHub token, e.g.
                > `git+https://<TOKEN>@github.com/...`.
                """
            )
        ),
        _code_cell("# Check the assigned GPU.\n!nvidia-smi"),
        _code_cell(
            textwrap.dedent(
                """\
                # Mount Google Drive (dataset in / trained model out).
                from google.colab import drive

                drive.mount('/content/drive')
                """
            )
        ),
        _code_cell(
            "# Install the BosesPH toolkit (with training extras) from GitHub.\n"
            f'!pip install -q "{_pip_install_spec(config)}"'
        ),
        _code_cell(_config_block(config)),
        _code_cell(
            textwrap.dedent(
                """\
                # Run fine-tuning on the GPU.
                from bosesph.finetune import finetune_model

                report = finetune_model(
                    dataset_dir,
                    output_dir,
                    base_model=base_model,
                    language=language,
                    epochs=epochs,
                    max_steps=max_steps,
                    batch_size=batch_size,
                    learning_rate=learning_rate,
                    train_split=train_split,
                    eval_split=eval_split,
                    gradient_checkpointing=gradient_checkpointing,
                    optim=optim,
                    use_lora=use_lora,
                    lora_r=lora_r,
                    lora_alpha=lora_alpha,
                    lora_dropout=lora_dropout,
                    fp16=fp16,
                    progress_fn=print,
                )

                print()
                print("Fine-tuning complete.")
                print("Model saved to:", report.model_path)
                print("Config:", report.config_path)
                print("Model card:", report.card_path)
                """
            )
        ),
        _markdown_cell(
            textwrap.dedent(
                f"""\
                ## Done

                Your fine-tuned model is in Drive at `{config.drive_output_path}`:

                - `model/` — the merged model + processor (load with
                  `transformers.pipeline`).
                - `model_card.md` — generated model card.
                - `training_config.json` — the exact training configuration.

                **Next steps:** download the `model/` directory, then evaluate it
                locally and run `bosesph compare` against your baseline.
                """
            )
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": []},
            "kernelspec": {
                "display_name": "Python 3",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }


def write_notebook(config: ColabExportConfig, output_path: str | Path) -> Path:
    """Write the generated notebook to ``output_path`` and return the path."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    notebook = build_notebook(config)
    out.write_text(json.dumps(notebook, indent=1) + "\n", encoding="utf-8")
    return out
